#!/bin/sh
#Use this to add packages to your machine when running wu_setup_dev
yum -y install ImageMagick.x86_64
yum -y install ImageMagick-devel.x86_64
yum -y install gperftools-libs.x86_64
yum -y install liboauth.x86_64
yum -y install liboauth-devel.x86_64

# Set up cloud9
yum -y install npm
cd ~
git clone https://github.com/ajaxorg/cloud9.git
cd cloud9
npm install
npm install -g forever
forever start server.js -l 0.0.0.0 -p 3131 -w /prod/www --username sam --password samsmaps37 -a x-www-broswer
cd ~

