#!/bin/sh
#Use this to add packages to your machine when running wu_setup_dev
yum -y install ImageMagick.x86_64
yum -y install ImageMagick-devel.x86_64
yum -y install gperftools-libs.x86_64
yum -y install liboauth.x86_64
yum -y install liboauth-devel.x86_64

# Install couchDB and start
#yum -y install couchdb
#couchdb -b

# Set up cloud9
yum -y install npm
#cd ~
#git clone https://github.com/ajaxorg/cloud9.git
#cd cloud9
#npm install
#npm install -g forever
#forever start server.js -l 0.0.0.0 -p 3131 -w /prod/www --username sam --password samsmaps37 -a x-www-broswer
#cd ~

npm install -g repl.history
npm install -g bower

# install dependencies for backbone-boilerplate
#npm install -g grunt-cli bower
#cd /prod/www/apache/htdocs/scripts/wumap
#npm install
#bower install
#cd ~

sh -c 'wget -qO- http://people.redhat.com/bkabrda/scl_python27.repo >> /etc/yum.repos.d/scl.repo'
yum -y install python27
yum -y install ctags

wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
python2.7 ez_setup.py
easy_install-2.7 pip

cd ~
git clone https://github.com/magicmonty/bash-git-prompt.git .bash-git-prompt
echo "\nsource ~/.bash-git-prompt/gitprompt.sh\nGIT_PROMPT_ONLY_IN_REPO=1\nGIT_PROMPT_END=\"\n\u@\h \t $ \"\n" >> ~/.bashrc
